name: Victor Mutelekesha
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c5c5'
    - '#94958f'
    - '#090b00'
    - '#42433d'
    - '#918f20'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
