name: Victor Mutelekesha
favicon: null
layout_spectrum: 0.84842
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#99a9b0'
    - '#6e8086'
    - '#3e282a'
    - '#72003b'
  brandStrength: 1
  lightness: 0
  saturation: 0.5966707349289209
  rhythmicContrast: 0.25
purpose: []
