typography_spectrum: 0.99929
color:
  brandColors:
    - '#c5c5c5'
    - '#94958f'
    - '#090b00'
    - '#42433d'
    - '#918f20'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Victor Mutelekesha
  email: victor.mutelekesha@gmail.com
name: Victor Mutelekesha
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Victor Mutelekesha
purpose: []
